#!/usr/bin/env php
<?php

use App\Commands\BuildOutcome;
use App\Commands\SlackBot;

require 'vendor/autoload.php';


$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$app = new Silly\Application();
$app->command('build [dateStr] [boardId]', [new BuildOutcome, 'run']);
$app->command('serve', [new SlackBot, 'run']);

try {
    $app->run();
} catch (Throwable $e) {
    echo "Oops {$e->getMessage()}";
}